# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crypta2.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crypta2.0
    pod 'web3swift'

end
